# name: Missing translation
name: 翻訳が存在しない
# description: Report a missing or incomplete translation (i.e. English showing)
description: 翻訳されていない場合や、不完全な翻訳を報告する（例：英語のままの場合など）
# title: "A brief title for your issue"
title: "問題のタイトル"
assignees:
  - nagix
  - yokawasa
body:
- type: markdown
  attributes:
    # value: '> **Note**: This form is for reporting missing or incomplete translations in the Japanese translation of Postman. For Postman functionality issues or problems that also exist in English, please report issues via the usual Postman support channels.'
    value: '> **メモ**: このフォームは、日本語版 Postman で翻訳がされていない場合や、不完全な翻訳を報告するためのものです。英語版 Postman 環境でも発生する機能障害や問題については、通常の [Postman サポートチャンネル](https://support.postman.com/hc/en-us)で報告してください。'
- type: textarea
  attributes:
    # label: Describe the Issue
    label: 問題の詳細
    # description: A high-level summary or description of the terminology issue, and how to access it in the Postman app
    description: 問題の要約、説明、および Postman アプリケーションでのアクセス方法を入力してください。
  validations:
    required: true
- type: markdown
  attributes:
    # value: '> **Note**: Remember that only the "Collections", "Environments" and "History" components of the Postman app, as well as the Settings page are currently fully translated into Japanese. While Japanese translations may show in other areas of the product, they are still a work-in-progress. Also remember that any data user-generated data such as Collection names will only appear in the language that they were created in.'
    value: '> **メモ**: 現時点では、Postman アプリケーションの[ワークスペース]、[コレクション]、[環境]、[履歴]コンポーネント、および[設定]ページのみが完全に日本語訳されています。 その他のプロダクト エリアでも日本語訳が表示されることがありますが、まだ作業中です。また、”コレクションの名前” のようなユーザー指定のデータは、入力された言語でのみ表示されます。'
- type: input
  id: currenttext
  attributes:
    # label: Current text
    label: 現在のテキスト
    # description: What is the text that is not translated or partially translated?
    description: 翻訳がされていない、または翻訳が不完全なテキストを入力してください。
    placeholder: 例： 新しいCollection
  validations:
    required: true
- type: textarea
  attributes:
    # label: Screenshots or Videos
    label: スクリーンショット／動画
    # description: | 
    # Please include screenshots or a short video showing where the untranslated wording appears in the Postman app
    #  Ensure that the screenshots/videos show the full screen of the Postman app and do not contain any sensitive information such as API keys or Access Tokens.
    description: | 
      日本語版 Postman アプリケーションの翻訳がされていないテキストが表示されたスクリーンショットか、短い動画を登録してください。
      スクリーンショット／動画は、API キーやアクセス トークンなどの機密情報が含まれていないことを確認し、Postman アプリケーション画面全体をキャプチャーしてください。 
  validations:
    required: true
- type: markdown
  attributes:
    # value: '> **Tip**: You can attach images and recordings to textareas by dragging in the files. More visual examples will help us to understand your concern.'
    value: '> **ヒント**: 画像や動画ファイルをテキストエリアにドラッグして、ファイルを添付できます。視覚的な例が多くあるほど、懸念箇所を理解しやすくなります。'
- type: dropdown
  attributes:
    # label: Postman Platform
    label: Postman プラットフォーム
    # description: In which Postman platform do you see this issue.
    description: 問題がある Postman プラットフォームを選択してください。
    # options:
    # - Postman App
    # - Postman Web
    # - Both
    options:
      - Postman デスクトップアプリ
      - Postman ウェブアプリ
      - 両方
  validations:
    required: true
- type: input
  attributes:
    # label: Operating System
    label: オペレーティング システム
    # description: Which OS are you using?
    description: 利用中の OS を入力してください。
    placeholder: "Windows/macOS/Linux"
  validations:
    required: true
- type: input
  attributes:
    # label: Postman Version
    label: Postman バージョン
    # description: Which version of the platform are you using? This can be found in 'General Settings > Settings > About'.
    description: 利用中のプラットフォームのバージョンを入力してください。バージョンを確認するには、[⚙ 設定] > [設定] > [概要]をクリックします。
    placeholder: "10.12.0"
  validations:
    required: true
- type: textarea
  attributes:
    # label: Additional comments or context?
    label: その他コメントやコンテキスト
    # description: |
    #  Please add any other comments or contextual information about the problem, that might be relevant and help explain the issue with the missing or incomplete translation.
    description: |
      翻訳がされていない、または不完全な翻訳の問題の理解を深めるために、適切なコメントやコンテキスト情報を入力してください。
  validations:
    required: false
